// MoonDocKit playground — drives the MoonBit renderer running in the browser.

const SAMPLES = {
  guide: `---
title: Feature Guide
order: 0
tags: [guide, features]
---
# Feature Guide

MoonDocKit turns Markdown and a MoonBit interface into a browsable site.

## Blocks

- headings, paragraphs, and lists
- fenced code blocks with language labels
- block quotes and inline \`code spans\`

> Run with \`--strict\` so validation warnings stop the build before publishing.

## Code

\`\`\`moonbit
fn greet(name : String) -> String {
  "Hello, \\\\{name}"
}
\`\`\`

### Inline Syntax

Use **strong text**, _emphasis_, and [links](https://moonbitlang.com).
`,
  api: `---
title: API Notes
order: 1
tags: [api, reference]
---
# API Notes

Every public function is extracted from \`pkg.generated.mbti\`.

## Functions

- \`mean(Array[Double]) -> Double\`
- \`median(Array[Double]) -> Double\`
- \`summarize(Array[Double]) -> Summary\`

## Types

\`\`\`moonbit
pub(all) struct Summary {
  count : Int
  mean : Double
  median : Double
}
\`\`\`

Anchors are generated per symbol, so deep links stay stable across releases.
`,
  tutorial: `---
title: Tutorial
order: 2
tags: [tutorial, setup]
---
# Build Your First Site

Three steps, one command each.

## 1. Write Pages

Put Markdown files in a directory and add front matter.

## 2. Build

\`\`\`bash
moon run --target js cmd/moondockit --config moondockit.json --strict
\`\`\`

## 3. Publish

Upload the output directory to any static host. The generated \`index.html\`
makes it work without extra configuration.
`,
  empty: "",
};

const editor = document.getElementById("editor");
const preview = document.getElementById("preview");
const metricsHost = document.getElementById("metrics");
const checksHost = document.getElementById("checks");
const statusEl = document.getElementById("status");
const titleInput = document.getElementById("title-input");
const themeSelect = document.getElementById("theme-select");
const sampleSelect = document.getElementById("sample-select");
const editorHint = document.getElementById("editor-hint");
const themeToggle = document.getElementById("theme-toggle");

let lastHtml = "";
let ready = false;

function setStatus(message, kind) {
  statusEl.textContent = message;
  statusEl.className = "status" + (kind ? " is-" + kind : "");
}

function waitFor(predicate, timeout) {
  const started = Date.now();
  return new Promise((resolve, reject) => {
    const tick = () => {
      if (predicate()) return resolve();
      if (Date.now() - started > timeout) return reject(new Error("timeout"));
      setTimeout(tick, 50);
    };
    tick();
  });
}

// The bundle is generated by `moon build --target js`. Load it as a module and
// fall back to a classic script so either output format works.
async function loadBridge() {
  try {
    await import("./moondockit-playground.js");
  } catch {
    await new Promise((resolve, reject) => {
      const tag = document.createElement("script");
      tag.src = "./moondockit-playground.js";
      tag.onload = resolve;
      tag.onerror = () => reject(new Error("classic script load failed"));
      document.head.appendChild(tag);
    });
  }
  await waitFor(() => typeof window.moonDocKitRenderPage === "function", 10000);
}

function parseStats(text) {
  const out = {};
  for (const line of String(text).split("\n")) {
    const index = line.indexOf("=");
    if (index > 0) out[line.slice(0, index)] = line.slice(index + 1);
  }
  return out;
}

function metric(label, value, state) {
  return `<div class="metric${state ? " is-" + state : ""}">
    <div class="label">${label}</div>
    <div class="value">${value}</div>
  </div>`;
}

function renderMetrics(stats) {
  const passed = stats.passed === "1";
  const cards = [
    metric("Quality score", stats.score ?? "—", passed ? "is-pass" : "is-fail"),
    metric("Publish gate", passed ? "Ready" : "Blocked", passed ? "is-pass" : "is-fail"),
    metric("Words", stats.words ?? "0"),
    metric("Headings", stats.headings ?? "0"),
    metric("Code blocks", stats.code_blocks ?? "0"),
    metric("Reading time", `${stats.reading_minutes ?? "0"} min`),
  ];
  metricsHost.innerHTML = cards.join("");

  const names = Object.keys(stats)
    .filter((key) => key.startsWith("check_"))
    .map((key) => key.slice(6));
  checksHost.innerHTML = names
    .map((name) => {
      const ok = stats["check_" + name] === "1";
      return `<span class="check ${ok ? "is-pass" : "is-fail"}">
        <span class="dot"></span>${name}
      </span>`;
    })
    .join("");
}

function render() {
  if (!ready) return;
  const markdown = editor.value;
  const title = titleInput.value.trim() || "Playground";
  editorHint.textContent = `${markdown.length} characters`;
  try {
    lastHtml = window.moonDocKitRenderPage(markdown, title, themeSelect.value);
    preview.srcdoc = lastHtml;
    renderMetrics(parseStats(window.moonDocKitPageStats(markdown, title)));
    setStatus("Rendered by MoonDocKit, compiled from MoonBit to JavaScript.");
  } catch (error) {
    setStatus(`Rendering failed: ${error.message}`, "error");
  }
}

function debounce(fn, wait) {
  let timer = 0;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), wait);
  };
}

const scheduleRender = debounce(render, 220);

editor.addEventListener("input", scheduleRender);
titleInput.addEventListener("input", scheduleRender);
themeSelect.addEventListener("change", render);

sampleSelect.addEventListener("change", () => {
  editor.value = SAMPLES[sampleSelect.value] ?? "";
  render();
});

document.getElementById("copy-btn").addEventListener("click", async () => {
  try {
    await navigator.clipboard.writeText(editor.value);
    setStatus("Markdown copied to the clipboard.");
  } catch {
    editor.select();
    setStatus(
      "Clipboard unavailable — the editor text is selected, press Ctrl+C.",
      "error",
    );
  }
});

document.getElementById("download-btn").addEventListener("click", () => {
  if (!lastHtml) return;
  const blob = new Blob([lastHtml], { type: "text/html" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "moondockit-page.html";
  link.click();
  URL.revokeObjectURL(link.href);
  setStatus("Downloaded the rendered page.");
});

themeToggle.addEventListener("click", () => {
  const dark = document.documentElement.getAttribute("data-theme") === "dark";
  document.documentElement.setAttribute("data-theme", dark ? "light" : "dark");
  themeToggle.textContent = dark ? "Dark mode" : "Light mode";
});

editor.value = SAMPLES.guide;

loadBridge()
  .then(() => {
    ready = true;
    render();
  })
  .catch((error) => {
    setStatus(
      `The MoonBit bundle did not load (${error.message}). Build it with ` +
        "`moon build --target js cmd/playground` and copy the output next to " +
        "this page as moondockit-playground.js.",
      "error",
    );
  });
